services:
 app-db:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: sagar#123
   volumes:
     - postgres-data:/var/lib/postgresql/data
   networks:
     - myAppNet
 adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080
   networks:
     - myAppNet
 app:
   image: padwalsagar/my-containerized-app:latest
   networks:
     - myAppNet
   ports:
     - 5000:80
   depends_on:
     - app-db
volumes:
 postgres-data:
    external: true
networks:
    myAppNet:
        name: postgres-net
  