services:
 app-db:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: sagar#123
   volumes:
     - postgres-data:/var/lib/postgresql/data
 adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080
 app:
   image: my-containerized-app:latest
   ports:
     - 5000:80
   depends_on:
     - app-db
volumes:
 postgres-data:
    external: true
networks:
    default:
        name: postgres-net
        external: true    
  